# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Country.create ([ { name: "Brazil", country_code: "BR" }, { name: "China", country_code: "CN" },
  { name: "Costa Rica", country_code: "CR" }, { name: "Egypt", country_code: "EG" }, { name: "Germany", country_code: "DE" },
  { name: "Greece", country_code: "GR" }, { name: "India", country_code: "IN" }, { name: "Italy", country_code: "IT" },
  { name: "Japan", country_code: "JP" }, { name: "Luxembourg", country_code: "LU" },
  { name: "Myanmar (Burma)", country_code: "MM" }, { name: "Netherlands", country_code: "NL" }, { name: "Nigeria", country_code: "NG" },
  { name: "Saudi Arabia", country_code: "SA" }, { name: "United States of America", country_code: "US" } ])

Factbook.create ([ { country_id: 1, population: 207353391, pop_yr: "July 2017", sex_ratio: 0.97,
    sex_ratio_yr: "2016", literacy_m: 92.2, literacy_f: 92.9, lit_yr: "2015", youth_unemploy_m: 13.8, youth_unemploy_f: 21.2, youth_unemploy_yr: "2014",
    gdp_per_capita: 15200, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 2, population: 1379302771, pop_yr: "July 2017", sex_ratio: 1.06,
    sex_ratio_yr: "2016", literacy_m: 98.2, literacy_f: 94.5, lit_yr: "2015", youth_unemploy_m: 0, youth_unemploy_f: 0, youth_unemploy_yr: "N/A",
    gdp_per_capita: 15400, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 3, population: 4930258, pop_yr: "2017", sex_ratio: 1.01,
    sex_ratio_yr: "2016", literacy_m: 97.7, literacy_f: 97.8, lit_yr: "2015", youth_unemploy_m: 18.8, youth_unemploy_f: 31.7, youth_unemploy_yr: "2016",
    gdp_per_capita: 16400, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 4, population: 97041072, pop_yr: "July 2017", sex_ratio: 1.05,
      sex_ratio_yr: "2016", literacy_m: 82.2, literacy_f: 65.4, lit_yr: "2015", youth_unemploy_m: 28.4, youth_unemploy_f: 37.6, youth_unemploy_yr: "2015",
      gdp_per_capita: 12600, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 5, population: 80594017, pop_yr: "July 2017", sex_ratio: 0.97,
      sex_ratio_yr: "2016", literacy_m: 0, literacy_f: 0, lit_yr: "N/A", youth_unemploy_m: 7.9, youth_unemploy_f: 6.5, youth_unemploy_yr: "2015",
      gdp_per_capita: 48400, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 6, population: 10768477, pop_yr: "July 2017", sex_ratio: 0.95,
      sex_ratio_yr: "2016", literacy_m: 98.5, literacy_f: 96.9, lit_yr: "2015", youth_unemploy_m: 45.2, youth_unemploy_f: 55, youth_unemploy_yr: "2015",
      gdp_per_capita: 26800, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 7, population: 1281935911, pop_yr: "July 2017", sex_ratio: 1.08,
      sex_ratio_yr: "2016", literacy_m: 81.3, literacy_f: 60.6, lit_yr: "2015", youth_unemploy_m: 10.4, youth_unemploy_f: 11.6, youth_unemploy_yr: "2012",
      gdp_per_capita: 6700, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 8, population: 62137802, pop_yr: "July 2017", sex_ratio: 0.93,
      sex_ratio_yr: "2016", literacy_m: 99.4, literacy_f: 99, lit_yr: "2015", youth_unemploy_m: 38.8, youth_unemploy_f: 42.6, youth_unemploy_yr: "2015",
      gdp_per_capita: 36800, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 9, population: 126451398, pop_yr: "July 2017", sex_ratio: 0.94,
      sex_ratio_yr: "2016", literacy_m: 0, literacy_f: 0, lit_yr: "N/A", youth_unemploy_m: 5.7, youth_unemploy_f: 4.5, youth_unemploy_yr: "2016",
      gdp_per_capita: 41200, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 10, population: 594130, pop_yr: "July 2017", sex_ratio: 1.01,
      sex_ratio_yr: "2016", literacy_m: 0, literacy_f: 0, lit_yr: "N/A", youth_unemploy_m: 18.9, youth_unemploy_f: 15.7, youth_unemploy_yr: "2015",
      gdp_per_capita: 105800, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 11, population: 55123814, pop_yr: "July 2017", sex_ratio: 0.99,
      sex_ratio_yr: "2016", literacy_m: 80, literacy_f: 71.8, lit_yr: "2016", youth_unemploy_m: 0, youth_unemploy_f: 0, youth_unemploy_yr: "N/A",
      gdp_per_capita: 5800, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 12, population: 17084719, pop_yr: "July 2017", sex_ratio: 0.98,
      sex_ratio_yr: "2016", literacy_m: 0, literacy_f: 0, lit_yr: "N/A", youth_unemploy_m: 11.3, youth_unemploy_f: 11.2, youth_unemploy_yr: "2015",
      gdp_per_capita: 51200, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 13, population: 190632261, pop_yr: "July 2017", sex_ratio: 1.04,
      sex_ratio_yr: "2016", literacy_m: 69.2, literacy_f: 49.7, lit_yr: "2015", youth_unemploy_m: 0, youth_unemploy_f: 0, youth_unemploy_yr: "N/A",
      gdp_per_capita: 5900, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 14, population: 28571770, pop_yr: "July 2017", sex_ratio: 1.19,
      sex_ratio_yr: "2016", literacy_m: 97, literacy_f: 91.1, lit_yr: "2015", youth_unemploy_m: 19.7, youth_unemploy_f: 56, youth_unemploy_yr: "2015",
      gdp_per_capita: 55300, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"},
  { country_id: 15, population: 326625971, pop_yr: "July 2017", sex_ratio: 0.97,
      sex_ratio_yr: "2016", literacy_m: 0, literacy_f: 0, lit_yr: "N/A", youth_unemploy_m: 11.4, youth_unemploy_f: 9.3, youth_unemploy_yr: "2016",
      gdp_per_capita: 57600, gdp_capita_yr: "2016", source_factbook: "CIA World Factbook"} ])

CountryFact.create ([ { country_id: 1, fact_1: "Brazil has been working to close the gender gap for the past two decades, with initiatives like Ciência sem Fronteiras, or the Brazil Scientific Mobility Program, to send 75,000 Brazilian students abroad for STEM education.", source_1: "http://mashable.com/2016/01/22/women-in-stem-global/#r88R.76r_uqX",
  fact_2: "Between 2011-2015, 49% of scientific scholarly articles were written by women.", source_2: "https://www.forbes.com/sites/shannonsims/2017/03/08/surprising-new-study-brazil-now-a-global-leader-in-gender-equality-in-science/#d6d79376f448",
  fact_3: "However, 1 in 4 women in Brazil typically leave the STEM field approximately 10 years into their career.", source_3: "http://www.catalyst.org/knowledge/women-science-technology-engineering-and-mathematics-stem",
  fact_4: "There are also cultural narratives the help keep women out of STEM. 'Girls play at home with dolls, and boys play with video games.' -Iana Chan", source_4: "http://www.americasquarterly.org/content/women-brazil-are-changing-world-tech-heres-how"},
  { country_id: 2, fact_1: "In general, women in China have disadvantages finding job opportunities due to having more family duties and expectations from society.", source_1: "N/A",
    fact_2: "In a 2015 study by the L'Oreal Foundation, it was found that in China 93% believe that women do not hold the necessary skillset to become scientists", source_2: "https://www.theguardian.com/women-in-leadership/2015/sep/24/67-of-europeans-dont-believe-women-have-the-skills-to-be-scientists",
    fact_3: "The government developed the 'Outline for the Development of Chinese Women 2011-2020' in attempt to raise the number of women in STEM to 35%", source_3: "http://www.scidev.net/global/capacity-building/news/china-aims-to-boost-number-of-women-scientists.html",
    fact_4: "The Chinese Young Women in Science Award was created in 2004 to help recognize the role of women in science and technology. So far, it has awarded 115 women.", source_4: "http://english.cast.org.cn/n214241/c353527/content.html"},
  { country_id: 3, fact_1: "Costa Rica is the first Central American country to pilot the TeachHer initiative to encourage girls and women in STEM fiels.", source_1: "http://www.ticotimes.net/2016/06/19/jill-biden-costa-rica-leader-gender-equality",
    fact_2: "The number of women graduating from universities has increased, and many women in Costa Rica have access to education, however, this hasn't translated into including women in the workforce. This may be because gender roles for men and women are traditional, with men expected to be the provider while women spend their week taking care of the household.", source_2: "http://www.ticotimes.net/2017/01/16/cynthia-castro-costa-rican-psychologist-fighting-gender-equality-global-level",
    fact_3: "The INAMU is working with municipalities and the private sector in Costa Rica to address issues of gender gaps and gender violence.", source_3: "http://www.ticotimes.net/2017/01/16/cynthia-castro-costa-rican-psychologist-fighting-gender-equality-global-level",
    fact_4: "In Central America, women employ 44% of all science and social science research positions, but continue to be underrepresented in STEM.", source_4: "https://www.reuters.com/article/us-latam-women-science-tech/latin-american-girls-hack-mans-world-of-tech-science-idUSKBN16E250"},
  { country_id: 4, fact_1: "2017 is the 'Year of Egyptian Women' according to President Abdel Fattah Al-Sisi, highlighting their central role for the future of Egypt and the need protect their constitutional rights.", source_1: "https://dailynewsegypt.com/2017/04/10/621604/",
    fact_2: "The female workforce in Egypt is 35%.", source_2: "https://dailynewsegypt.com/2017/04/10/621604/",
    fact_3: "Men are represented 3 times more than women in the workforce.", source_3: "https://www.al-monitor.com/pulse/fr/originals/2015/11/egypt-women-participation-labor-market.html",
    fact_4: "Egyptian women have a limited ability to work due to balancing career and family, unwillingness to hire a woman who has a child, gender discrimination in the workforce, and harassment.", source_4: "https://www.al-monitor.com/pulse/fr/originals/2015/11/egypt-women-participation-labor-market.html"},
  { country_id: 5, fact_1: "Germany has over 35,000 vacant engineering jobs. The Association of German Engineers is working to fill these positions with women.", source_1: "http://www.spiegel.de/international/germany/germany-boosts-efforts-to-get-women-in-stem-fields-a-924023.html",
    fact_2: "The gender gap in STEM is 19.3%", source_2: "http://www.catalyst.org/knowledge/women-science-technology-engineering-and-mathematics-stem",
    fact_3: "Women in Germany earn approximately 21.6% less than men, and is one of the biggest gender wage gaps in Europe.", source_3: "http://www.dw.com/en/study-german-wage-gap-between-men-and-women-among-europes-biggest/a-19086382",
    fact_4: "In 2014, 29% of women had managerial positions in Germany compared to the EU average of 33%", source_4: "http://www.dw.com/en/women-in-germany-await-workplace-equality/a-19099867"},
  { country_id: 6, fact_1: "About 45% of women in employeed in Greece, compared to the EU-27 countries which have an average of 58.5%", source_1: "http://ec.europa.eu/justice/gender-equality/files/epo_campaign/130911_country-profile_greece.pdf",
    fact_2: "37.6% of women are employeed in Science, Maths, and Computers and 26% in Engineering", source_2: "http://ec.europa.eu/justice/gender-equality/files/epo_campaign/130911_country-profile_greece.pdf",
    fact_3: "Greece has a large gender wage gap, with women receiving 51.7% of what their male counterparts are paid.", source_3: "http://www.ekathimerini.com/222916/article/ekathimerini/business/labor-market-continues-to-suffer",
    fact_4: "Important women in science - Hypatia, Agnodike, and Aspasia of Miletus to name a few - can be found in Ancient Greek history, although their contributions are often unnoticed and forgotten.", source_4: "http://nautil.us/blog/its-time-these-ancient-women-scientists-get-their-due"},
  { country_id: 7, fact_1: "India is ranked 120/131 countries for women's participation in the workforce.", source_1: "http://www.hindustantimes.com/india-news/india-ranks-120th-among-131-nations-in-women-workforce-says-world-bank-report/story-Q5AVD5aRlmLHA1RAFpnZuJ.html",
    fact_2: "Only 27% of Indian women work.", source_2: "http://fortune.com/2015/03/05/women-in-the-workforce/",
    fact_3: "The World Bank believes that the decrease of Indian women in the workforce is due to lack of job opportunities for women, an increase in women and girls attending school, rise in household income, and decrease in child labor.", source_3: "http://www.hindustantimes.com/analysis/why-indian-women-are-leaving-the-workforce/story-V7Qlyp2P3wlb2ZPLcINuNI.html",
    fact_4: "Indian universities trains more engineers than the United States and China combined. Women accounting for 28.5%", source_4: "https://research.swe.org/2016/08/india/"},
  { country_id: 8, fact_1: "In 2016, women made up 42% of Italy's workforce, an increase from 36% in 1990.", source_1: "https://data.worldbank.org/indicator/SL.TLF.TOTL.FE.ZS",
    fact_2: "Male STEM researchers are promoted twice as much as female STEM researchers.", source_2: "http://science.sciencemag.org/content/295/5553/278",
    fact_3: "There are fewer than 1/10 women who occupy a seat on Boards of large STEM companies.", source_3: "https://www.kellyservices.com/global/siteassets/3-kelly-global-services/uploadedfiles/kocg1076820women20in20stem20ebook.pdf",
    fact_4: "Women's achievements in Italy surrounding employment and income are threatened by policies aimed to reduce the government's budget deficits and the financial crisis.", source_4: "http://www.europarl.europa.eu/RegData/etudes/note/join/2014/493052/IPOL-FEMM_NT(2014)493052_EN.pdf"},
  { country_id: 9, fact_1: "Female participation in the workforce has continued to increase, and was 66% in 2014, while female unemployment was 3.5%", source_1: "http://www.businessinsider.com/japanese-women-entering-workforce-2016-4",
    fact_2: "13% of STEM university professors in Japan are female.", source_2: "https://medium.com/neurographic/in-japan-women-in-science-seek-allies-resources-in-push-for-gender-equality-3a8ec6adb9a0",
    fact_3: "Japan aims to increase the percentage of mothers who return to the workforce to 55%", source_3: "https://www.washingtonpost.com/world/asia_pacific/japanese-leader-abe-wants-more-women-to-work-so-hes-got-big-plans-for-day-care/2014/08/01/8dcd84f5-c4b2-4e39-a1e0-125eaa57309b_story.html?utm_term=.c1ceac34c2b0",
    fact_4: "Prime Minister Shinzo Abe's Abenomics was nicknamed 'womenomics' to help encourage more women to join the workforce.", source_4: "http://www.businessinsider.com/japanese-women-entering-workforce-2016-4"},
  { country_id: 10, fact_1: "Luxembourg has one of the largest employment gaps in Europe for women (76.5%) and men (91.6%) in the workforce.", source_1: "http://www.luxembourg.public.lu/en/le-grand-duche-se-presente/population/femmes/index.html",
    fact_2: "Along with the Netherlands and Turkey, Luxembourg is one of the bottom European countries for new women entering STEM.", source_2: "http://www.oecd-ilibrary.org/docserver/download/9617041ec058.pdf?expires=1511984010&id=id&accname=guest&checksum=40E6C68091A734CA872E507329F6D194",
    fact_3: "Part-time work is reserved almost primarily for women in Luxembourg.", source_3: "http://www.luxembourg.public.lu/en/le-grand-duche-se-presente/population/femmes/index.html",
    fact_4: "Luxembourg has one of the lowest accesibility rates from women looking to become a professor in Europe.", source_4: "http://www.sciencemag.org/careers/2013/04/gender-equality-european-research"},
  { country_id: 11, fact_1: "In 2013, only 3.4% of women were elected to Myanmar's Parliament.", source_1: "http://warwickaseanconference.com/womens-rights-in-myanmar-a-work-in-progress/",
    fact_2: "Women's participation in the workforce is 53.9% compared to 82.1% for men.", source_2: "http://warwickaseanconference.com/womens-rights-in-myanmar-a-work-in-progress/",
    fact_3: "Despite this gap, Myanmar is ranked 83/144 countries for its gender gap. Higher than both China and South Korea.", source_3: "https://www.mmtimes.com/news/raising-role-women-myanmar-economy.html",
    fact_4: "According to UNESCO, Myanmar has one of the highest ratios of female STEM researchers in Asia. 70 out of 100 researchers are women.", source_4: "https://www.mmtimes.com/news/raising-role-women-myanmar-economy.html"},
  { country_id: 12, fact_1: "The Netherlands is one of the weakest countries when it comes to the representation of women in STEM - notably science - fields.", source_1: "http://www.slate.com/blogs/better_life_lab/2017/11/09/the_stem_paradox_why_are_muslim_majority_countries_producing_so_many_female.html",
    fact_2: "Approximately 4% of full-time professors are women.", source_2: "https://www.theatlantic.com/magazine/archive/2017/09/the-queen-bee-in-the-corner-office/534213/",
    fact_3: "77% of women work part-time in the Netherlands, which is the highest percentage in the EU.", source_3: "https://www.independent.ie/business/in-the-workplace/high-percentage-of-women-decline-to-return-to-work-after-third-child-36296161.html",
    fact_4: "Between March 2015 and May 2015 the number of women employed increased by approximately 6,000 a month.", source_4: "https://www.cbs.nl/en-gb/news/2015/25/more-women-employed"},
  { country_id: 13, fact_1: "According to the African Development Bank, women make up almost 70% of the agriculture workforce.", source_1: "https://www.vanguardngr.com/2015/10/nigerian-women-contribute-almost-70-agric-workforce-afdb/",
    fact_2: "However, nation wide women make up 42.7% of the workforce.", source_2: "https://data.worldbank.org/indicator/SL.TLF.TOTL.FE.ZS",
    fact_3: "The African Development Bank emphasizes gender equality in the workforce within the strategy for Nigeria from 2012-2022.", source_3: "https://www.vanguardngr.com/2015/10/nigerian-women-contribute-almost-70-agric-workforce-afdb/",
    fact_4: "Since its launch in 2013, She Will Connect Africa has trained more than 150,000 women in Nigeria, South Africa and Kenya in digital literacy and programming.", source_4: "https://www.theguardian.com/lifeandstyle/2017/aug/14/breaking-the-code-how-women-in-nigeria-are-changing-the-face-of-tech"},
  { country_id: 14, fact_1: "One of the national goals in Saudi Arabia is to increase the percentage of women in the workforce to 30% while reducing female unemployment to 7% by 2030.", source_1: "https://www.ft.com/content/c55d6cf4-8cd3-11e7-9084-d0c17942ba93",
    fact_2: "Hoping to create 141,000 jobs for women, the National Transformation Program 2020 launched a program that allows women to work from home.", source_2: "http://saudigazette.com.sa/article/512279/SAUDI-ARABIA/Saudi-Arabia",
    fact_3: "In 2011, King Abdullah allowed women to vote in municipal elections and compete in the Olympics.", source_3: "http://www.independent.co.uk/news/world/middle-east/saudi-arabia-male-guardianship-relax-women-work-study-gender-equality-a7721641.html",
    fact_4: "According to UNESCO, in the Gulf region women make up 60% of university engineering students, compared to 30% in the US and Europe.", source_4: "https://www.usnews.com/education/best-arab-region-universities/articles/2015/03/04/more-arab-women-studying-stem"},
  { country_id: 15, fact_1: "In the US, women make up almost 50% of the workforce, however, they only account for 25% of STEM jobs.", source_1: "http://www.esa.doc.gov/sites/default/files/womeninstemagaptoinnovation8311.pdf",
    fact_2: "Women with a STEM degree are more likely to end up in healthcare or education.", source_2: "http://www.esa.doc.gov/sites/default/files/womeninstemagaptoinnovation8311.pdf",
    fact_3: "Approximately, 1/7 engineers are female, and 49% of women in STEM under the age of 29 are looking for employment.", source_3: "http://www.esa.doc.gov/sites/default/files/womeninstemagaptoinnovation8311.pdf",
    fact_4: "Women in STEM careers make approximately $31.11/hour compared to $36.34/hour for men.", source_4: "http://www.esa.doc.gov/sites/default/files/womeninstemagaptoinnovation8311.pdf"} ])
